watch:
  directories:
    - config
    - public
    - src
    - tests
  fileMask: '*.php'
notifications:
  passingTests: false
  failingTests: false
phpunit:
  arguments: '--stop-on-failure --testdox --coverage-text'
